server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
logging:
  level:
    ROOT: INFO
spring:
  application:
    name: event-driven-architecture
