server:
  port: 8080
logging:
  level:
    ROOT: INFO
spring:
  application:
    name: myPrimobox
  jms:
    template:
      default-destination: jms.queue.myprimobox-local
    pub-sub-domain: true
  artemis:
    broker-url: tcp://localhost:61616
    user: demat
    password: CR4oo&Asza#9
