name: Build and deploy app
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout des sources
        run: git clone https://github.com/Primobox/event-driven-architecture.git
        shell: bash
      - name: Mise à jour des sources
        if: always()
        run: git pull
        shell: bash
      - name: Build
        run: docker build -t primobox/event-driven-architecture:latest .
        shell: bash
      - name: Arrêt/Démarrage de l'application
        if: always()
        run: docker rm -v -f event-driven-architecture | true && docker run -d --name event-driven-architecture -p 8080:8080 -e SPRING_SECURITY_USER_NAME=$SPRING_SECURITY_USER_NAME -e SPRING_SECURITY_USER_PASSWORD=$SPRING_SECURITY_USER_PASSWORD primobox/event-driven-architecture:latest
        shell: bash
