name: Build and deploy app
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Display the path
        run: echo $PATH
        shell: bash
      - name: Display directory content
        run: ls -lah
        shell: bash
      - name: Display current directory
        run: pwd
        shell: bash