name: Build and deploy app
on:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Mise à jour des sources
        run: git pull
        shell: bash
      - name: Build
        run: docker build -t primobox/event-driven-architecture:latest .
        shell: bash
      - name: Arrêt de l'application
        run: docker rm -v -f event-driven-architecture | true
        shell: bash
      - name: Démarrage de l'application
        env:
          SPRING_SECURITY_USER_NAME: ${{ secrets.SPRING_SECURITY_USER_NAME }}
          SPRING_SECURITY_USER_PASSWORD: ${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
        if: always()
        run: docker run -d --name event-driven-architecture -p 8080:8080 -e SPRING_SECURITY_USER_NAME=$SPRING_SECURITY_USER_NAME -e SPRING_SECURITY_USER_PASSWORD=$SPRING_SECURITY_USER_PASSWORD primobox/event-driven-architecture:latest
        shell: bash
